# Generated by Django 4.0.1 on 2022-02-17 09:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vans', '0006_remove_van_daily_rate_april_june_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.EmailField(max_length=254)),
                ('number_of_people', models.IntegerField(default=0)),
                ('number_of_days', models.IntegerField(default=0)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
            ],
        ),
    ]
