# Generated by Django 4.0.1 on 2022-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('van_name', models.CharField(max_length=254)),
                ('van_description', models.TextField()),
                ('size_description', models.CharField(max_length=254)),
                ('fuel_type', models.CharField(max_length=254)),
                ('sleeps', models.CharField(max_length=254)),
                ('seats', models.CharField(max_length=254)),
                ('airconditioning_home_area', models.BooleanField(blank=True, default=False, null=True)),
                ('awning', models.BooleanField(blank=True, default=False, null=True)),
                ('refrigerator', models.BooleanField(blank=True, default=False, null=True)),
                ('shower', models.BooleanField(blank=True, default=False, null=True)),
                ('camping_table_chairs', models.BooleanField(blank=True, default=False, null=True)),
                ('gas_cylinder', models.BooleanField(blank=True, default=False, null=True)),
                ('solar_panel', models.BooleanField(blank=True, default=False, null=True)),
                ('toilet', models.BooleanField(blank=True, default=False, null=True)),
                ('heating', models.BooleanField(blank=True, default=False, null=True)),
                ('hot_water', models.BooleanField(blank=True, default=False, null=True)),
                ('tv', models.BooleanField(blank=True, default=False, null=True)),
                ('tv_receiver', models.BooleanField(blank=True, default=False, null=True)),
                ('kitchen_equipment', models.BooleanField(blank=True, default=False, null=True)),
                ('airconditioning_cabin', models.BooleanField(blank=True, default=False, null=True)),
                ('reversing_camera', models.BooleanField(blank=True, default=False, null=True)),
                ('roof_rack', models.BooleanField(blank=True, default=False, null=True)),
                ('towbar', models.BooleanField(blank=True, default=False, null=True)),
                ('cruise_control', models.BooleanField(blank=True, default=False, null=True)),
                ('gps', models.BooleanField(blank=True, default=False, null=True)),
                ('power_steering', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_bike_rack', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_awning', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_towbar', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_travel_box', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_chemical_toilet', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_bbq', models.BooleanField(blank=True, default=False, null=True)),
                ('extras_cutlery_crockery', models.BooleanField(blank=True, default=False, null=True)),
                ('van_main_image', models.URLField(blank=True, max_length=1024, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('daily_rate_december_march', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_rate_april_june', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_rate_july_september', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_rate_october_november', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mileage_limit', models.CharField(max_length=254)),
                ('price_per_extra_mile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motorhome_insurance', models.CharField(max_length=254)),
                ('breakdown_cover', models.CharField(max_length=254)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
