# Generated by Django 4.0.1 on 2022-01-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vans',
            new_name='Van',
        ),
    ]
