# Generated by Django 4.0.1 on 2022-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0002_rename_vans_van'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='mileage_limit',
            field=models.CharField(default='1000km', max_length=254),
        ),
    ]
