# Generated by Django 4.0.1 on 2022-01-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0004_alter_van_airconditioning_cabin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='price_per_extra_mile',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
